/*
 * This file is auto-generated by ./bin/rails stimulus:manifest:update
 * Run that command whenever you add a new controller or create them with
 * ./bin/rails generate stimulus controllerName
 */

import {application} from "./application";

import DialogController from "./dialog_controller";
application.register("dialog", DialogController);

import EnclosureDownloadController from "./enclosure_download_controller";
application.register("enclosure-download", EnclosureDownloadController);

import HotkeysController from "./hotkeys_controller";
application.register("hotkeys", HotkeysController);
