// This configuration was generated by `exe/eslint_autogen`
// on 2026-02-15 05:36:35 UTC.
// The point is for the user to remove these configuration records
// one by one as the offenses are removed from the code base.

import type {Linter} from "eslint";

const config: Linter.Config[] = [
  // Offense count: 15
  {
    files: [
      "spec/javascript/setup.ts",
      "vitest.config.ts",
    ],
    rules: {
      "@stylistic/max-len": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "@stylistic/multiline-comment-style": "off",
    },
  },
  // Offense count: 30
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "@stylistic/object-curly-spacing": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/application.ts",
    ],
    rules: {
      "import/no-unresolved": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "stylelint.config.mjs",
    ],
    rules: {
      "@stylistic/quote-props": "off",
    },
  },
  // Offense count: 41
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "@stylistic/quotes": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "@typescript-eslint/ban-ts-comment": "off",
    },
  },
  // Offense count: 7
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "@typescript-eslint/explicit-function-return-type": "off",
    },
  },
  // Offense count: 45
  {
    files: [
      "eslint.config.mts",
      "spec/javascript/setup.ts",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
    },
  },
  // Offense count: 181
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-call": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "capitalized-comments": "off",
    },
  },
  // Offense count: 111
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "func-names": "off",
    },
  },
  // Offense count: 15
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "id-length": "off",
    },
  },
  // Offense count: 12
  {
    files: [
      "spec/javascript/setup.ts",
      "vitest.config.ts",
    ],
    rules: {
      "max-len": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "new-cap": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "prefer-named-capture-group": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "require-unicode-regexp": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "sort-imports": "off",
    },
  },
  // Offense count: 26
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "sort-keys": "off",
    },
  },
  // Offense count: 26
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "sort-keys-fix/sort-keys-fix": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "vitest/require-hook": "off",
    },
  },
];

export default config;
