inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  EnabledByDefault: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/LineLength: { Max: 80 }
Metrics/BlockLength: { Exclude: ['spec/**/*_spec.rb'] }
Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - to
    - not_to
    - describe
Style/StringLiterals: { EnforcedStyle: double_quotes }

# want to enable these, but they don't work right when using `.rubocop_todo.yml`
Style/DocumentationMethod: { Enabled: false }
Style/Documentation: { Enabled: false }

################################################################################
#
# Rules we don't want to enable
#
################################################################################

Lint/ConstantResolution: { Enabled: false }
Rails/SchemaComment: { Enabled: false }
RSpec/StubbedMock: { Enabled: false }
Style/InlineComment: { Enabled: false }
Style/RequireOrder: { Enabled: false }
Style/SafeNavigation: { Enabled: false }
Style/ConstantVisibility: { Enabled: false }
Style/Copyright: { Enabled: false }
Style/MissingElse: { Enabled: false }
