inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  EnabledByDefault: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 15

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
