version: 2.1

orbs:
  browser-tools: circleci/browser-tools@2.2.0
  node: circleci/node@7.1.0

executors:
  default:
    resource_class: large
    docker:
      - image: cimg/ruby:4.0.6-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: cimg/postgres:10.18
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD:

commands:
  setup:
    description: Check out code and install Node, Ruby, and database dependencies
    steps:
      - checkout

      - node/install:
          node-version: 26.8.2
          install-pnpm: true
          pnpm-version: 12.5.1

      - node/install-packages:
          pkg-manager: pnpm

      - run:
          name: Which versions?
          command: |
            bundle -v
            node --version
            pnpm --version

      # https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - bundle-v2-{{ checksum "Gemfile.lock" }}
            - bundle-v2

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: |
            bundle config set --local frozen 'true'
            bundle install
            bundle clean

      - save_cache:
          key: bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:setup --trace

jobs:
  checks:
    executor: default
    steps:
      - setup

      - run:
          name: Typescript
          command: pnpm tscheck

      - run:
          name: Find Unused ESLint Rules
          command: pnpm eslint_find_unused_rules

      - run:
          name: ESLint
          command: pnpm eslint

      - run:
          name: Verify ESLint Autogen
          command: bundle exec exe/eslint_autogen

      - run:
          name: Vitest
          command: pnpm vitest run --coverage

      - run:
          name: Brakeman
          command: bundle exec brakeman

      - run:
          name: Stylelint
          command: pnpm stylelint

      - run:
          name: Verify Stylelint Autogen
          command: bundle exec exe/stylelint_autogen

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: ✨ 🌈 ✨ Run Unit Tests ✨ 🌈 ✨
          command: |
            COVERAGE=true bundle exec rspec \
              --exclude-pattern "spec/system/**/*_spec.rb" \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/unit/rspec.xml

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: log
          destination: log

  system_tests:
    executor: default
    parallelism: 4
    steps:
      - setup

      - browser-tools/install_firefox

      - run:
          name: ✨ 🌈 ✨ Run System Tests ✨ 🌈 ✨
          command: |
            TEST_FILES="$(circleci tests glob "spec/system/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            echo "******************** TEST_FILES ************************"
            echo "bundle exec rspec -s <seed-from-failed-build> $TEST_FILES"
            echo "********************************************************"

            mkdir -p tmp/capybara

            COVERAGE=false xvfb-run -a bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/system/rspec.xml \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: tmp/capybara
          destination: capybara

      - store_artifacts:
          path: log
          destination: log

workflows:
  test:
    jobs:
      - checks
      - system_tests
